import {
  AnimeOngoingItem,
  AnimeDetail,
  EpisodeStreamData,
  DonghuaItem,
  DonghuaDetail,
  DonghuaEpisodeStream,
  ComicItem,
  ComicDetail,
  ChapterItem,
  ChapterReaderData,
  GenreItem,
  ScheduleDay,
  ComicScheduleDay,
  ComicScheduleEntry,
} from '@/types/api';

// --- ANIME ONGOING (24 Items) ---
export const mockAnimeOngoing: AnimeOngoingItem[] = [
  {
    title: 'Solo Leveling: Arise from the Shadow',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    episodes: 12,
    releaseDay: 'Sabtu',
    latestReleaseDate: '23 Sep',
    releasedOn: '1 jam yang lalu',
    animeId: 'solo-leveling-s2',
    href: '/anime/otakudesu/solo-leveling-s2',
  },
  {
    title: 'Jujutsu Kaisen: Culling Game Arc',
    poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    episodes: 8,
    releaseDay: 'Kamis',
    latestReleaseDate: '22 Sep',
    releasedOn: '5 jam yang lalu',
    animeId: 'jujutsu-kaisen-s3',
    href: '/anime/otakudesu/jujutsu-kaisen-s3',
  },
  {
    title: "Frieren: Beyond Journey's End S2",
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    episodes: 6,
    releaseDay: 'Jumat',
    latestReleaseDate: '21 Sep',
    releasedOn: '1 hari yang lalu',
    animeId: 'frieren-s2',
    href: '/anime/otakudesu/frieren-s2',
  },
  {
    title: 'Chainsaw Man: Reze Arc',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    episodes: 2,
    releaseDay: 'Minggu',
    latestReleaseDate: '20 Sep',
    releasedOn: '2 hari yang lalu',
    animeId: 'chainsaw-man-reze',
    href: '/anime/otakudesu/chainsaw-man-reze',
  },
  {
    title: 'Demon Slayer: Infinity Castle Arc',
    poster: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
    episodes: 4,
    releaseDay: 'Minggu',
    latestReleaseDate: '19 Sep',
    releasedOn: '3 hari yang lalu',
    animeId: 'demon-slayer-infinity-castle',
    href: '/anime/otakudesu/demon-slayer-infinity-castle',
  },
  {
    title: 'Bleach: Thousand-Year Blood War Pt. 3',
    poster: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    episodes: 32,
    releaseDay: 'Senin',
    latestReleaseDate: '18 Sep',
    releasedOn: '4 hari yang lalu',
    animeId: 'bleach-tybw-pt3',
    href: '/anime/otakudesu/bleach-tybw-pt3',
  },
  {
    title: 'Blue Lock Season 2: U-20 Match',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    episodes: 5,
    releaseDay: 'Selasa',
    latestReleaseDate: '17 Sep',
    releasedOn: '5 hari yang lalu',
    animeId: 'blue-lock-s2',
    href: '/anime/otakudesu/blue-lock-s2',
  },
  {
    title: 'Shangri-La Frontier S2',
    poster: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    episodes: 7,
    releaseDay: 'Jumat',
    latestReleaseDate: '16 Sep',
    releasedOn: '6 hari yang lalu',
    animeId: 'shangri-la-frontier-s2',
    href: '/anime/otakudesu/shangri-la-frontier-s2',
  },
  {
    title: 'Tower of God Season 2: Workshop Battle',
    poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    episodes: 12,
    releaseDay: 'Senin',
    latestReleaseDate: '15 Sep',
    releasedOn: '1 minggu yang lalu',
    animeId: 'tower-of-god-s2',
    href: '/anime/otakudesu/tower-of-god-s2',
  },
  {
    title: 'Kaiju No. 8 Season 2',
    poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    episodes: 12,
    releaseDay: 'Sabtu',
    latestReleaseDate: '14 Sep',
    releasedOn: '1 minggu yang lalu',
    animeId: 'kaiju-no-8-s2',
    href: '/anime/otakudesu/kaiju-no-8-s2',
  },
  {
    title: 'DanMachi Season 5: Goddess of Harvest',
    poster: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    episodes: 9,
    releaseDay: 'Kamis',
    latestReleaseDate: '13 Sep',
    releasedOn: '1 minggu yang lalu',
    animeId: 'danmachi-s5',
    href: '/anime/otakudesu/danmachi-s5',
  },
  {
    title: 'Oshi no Ko Season 2: 2.5D Stage Play',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    episodes: 11,
    releaseDay: 'Rabu',
    latestReleaseDate: '12 Sep',
    releasedOn: '1 minggu yang lalu',
    animeId: 'oshi-no-ko-s2',
    href: '/anime/otakudesu/oshi-no-ko-s2',
  },
  {
    title: 'Wind Breaker: Bofurin Legend',
    poster: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80',
    episodes: 13,
    releaseDay: 'Selasa',
    latestReleaseDate: '11 Sep',
    releasedOn: '1 minggu yang lalu',
    animeId: 'wind-breaker',
    href: '/anime/otakudesu/wind-breaker',
  },
  {
    title: 'One Piece: Egghead Island Climax',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    episodes: 1125,
    releaseDay: 'Minggu',
    latestReleaseDate: '10 Sep',
    releasedOn: '1 minggu yang lalu',
    animeId: 'one-piece',
    href: '/anime/otakudesu/one-piece',
  },
  {
    title: 'My Hero Academia Season 7',
    poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    episodes: 21,
    releaseDay: 'Sabtu',
    latestReleaseDate: '09 Sep',
    releasedOn: '2 minggu yang lalu',
    animeId: 'my-hero-academia-s7',
    href: '/anime/otakudesu/my-hero-academia-s7',
  },
  {
    title: 'Re:Zero - Starting Life in Another World S3',
    poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    episodes: 16,
    releaseDay: 'Rabu',
    latestReleaseDate: '08 Sep',
    releasedOn: '2 minggu yang lalu',
    animeId: 're-zero-s3',
    href: '/anime/otakudesu/re-zero-s3',
  },
  {
    title: 'Mushoku Tensei: Jobless Reincarnation S2 Pt. 2',
    poster: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    episodes: 24,
    releaseDay: 'Minggu',
    latestReleaseDate: '07 Sep',
    releasedOn: '2 minggu yang lalu',
    animeId: 'mushoku-tensei-s2',
    href: '/anime/otakudesu/mushoku-tensei-s2',
  },
  {
    title: 'That Time I Got Reincarnated as a Slime S3',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    episodes: 24,
    releaseDay: 'Jumat',
    latestReleaseDate: '06 Sep',
    releasedOn: '2 minggu yang lalu',
    animeId: 'tensei-shitara-slime-s3',
    href: '/anime/otakudesu/tensei-shitara-slime-s3',
  },
  {
    title: 'The Eminence in Shadow Movie: Lost Echoes',
    poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    episodes: 1,
    releaseDay: 'Sabtu',
    latestReleaseDate: '05 Sep',
    releasedOn: '2 minggu yang lalu',
    animeId: 'eminence-in-shadow-movie',
    href: '/anime/otakudesu/eminence-in-shadow-movie',
  },
  {
    title: 'Black Clover: Spade Kingdom Arc Continued',
    poster: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
    episodes: 175,
    releaseDay: 'Selasa',
    latestReleaseDate: '04 Sep',
    releasedOn: '2 minggu yang lalu',
    animeId: 'black-clover-spade',
    href: '/anime/otakudesu/black-clover-spade',
  },
  {
    title: 'Dr. STONE: Science Future',
    poster: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    episodes: 12,
    releaseDay: 'Kamis',
    latestReleaseDate: '03 Sep',
    releasedOn: '3 minggu yang lalu',
    animeId: 'dr-stone-science-future',
    href: '/anime/otakudesu/dr-stone-science-future',
  },
  {
    title: 'Vinland Saga Season 3: Eastern Expedition',
    poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    episodes: 10,
    releaseDay: 'Senin',
    latestReleaseDate: '02 Sep',
    releasedOn: '3 minggu yang lalu',
    animeId: 'vinland-saga-s3',
    href: '/anime/otakudesu/vinland-saga-s3',
  },
  {
    title: "Hell's Paradise Season 2 (Jigokuraku)",
    poster: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    episodes: 8,
    releaseDay: 'Sabtu',
    latestReleaseDate: '01 Sep',
    releasedOn: '3 minggu yang lalu',
    animeId: 'hells-paradise-s2',
    href: '/anime/otakudesu/hells-paradise-s2',
  },
  {
    title: 'Kingdom Season 6: Western Zhao Invasion',
    poster: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80',
    episodes: 14,
    releaseDay: 'Minggu',
    latestReleaseDate: '30 Aug',
    releasedOn: '3 minggu yang lalu',
    animeId: 'kingdom-s6',
    href: '/anime/otakudesu/kingdom-s6',
  },
];

export const mockAnimeDetail: AnimeDetail = {
  title: 'Solo Leveling: Arise from the Shadow',
  poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
  japanese: '俺だけレベルアップな件',
  score: 8.95,
  producers: 'Aniplex, Crunchyroll',
  type: 'TV Series',
  status: 'Ongoing',
  episodes: 12,
  duration: '24 menit per episode',
  aired: 'Jan 2026 - Present',
  studios: 'A-1 Pictures',
  synopsis: `Di dunia di mana pemburu berkekuatan sihir melawan monster mematikan untuk melindungi umat manusia, Sung Jin-Woo—seorang pemburu tingkat E yang dikenal sebagai 'yang terlemah di dunia'—menemukan dungeon ganda misterius.\n\nSetelah selamat dari ujian maut, dia terbangun dengan sebuah 'Sistem' misterius yang hanya bisa dilihat olehnya, memberinya kekuatan unik untuk naik level tanpa batas.`,
  genreList: [
    { title: 'Action', href: '/genre/action', slug: 'action' },
    { title: 'Fantasy', href: '/genre/fantasy', slug: 'fantasy' },
    { title: 'Super Power', href: '/genre/super-power', slug: 'super-power' },
    { title: 'Shounen', href: '/genre/shounen', slug: 'shounen' },
  ],
  episodeList: [
    {
      title: 'Episode 12 - The Monarch Arises (Sub Indo)',
      episodeId: 'solo-leveling-ep-12',
      href: '/watch/otakudesu/solo-leveling-ep-12',
      date: '23 Sep 2026',
    },
    {
      title: 'Episode 11 - Shadows of the Red Gate',
      episodeId: 'solo-leveling-ep-11',
      href: '/watch/otakudesu/solo-leveling-ep-11',
      date: '16 Sep 2026',
    },
    {
      title: 'Episode 10 - Guild Strike Command',
      episodeId: 'solo-leveling-ep-10',
      href: '/watch/otakudesu/solo-leveling-ep-10',
      date: '09 Sep 2026',
    },
    {
      title: 'Episode 1 - The Weakest Hunter E-Rank',
      episodeId: 'solo-leveling-ep-1',
      href: '/watch/otakudesu/solo-leveling-ep-1',
      date: '01 Juli 2026',
    },
  ],
  recommendedAnimeList: [
    {
      title: 'Jujutsu Kaisen',
      poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
      animeId: 'jujutsu-kaisen-s3',
      href: '/anime/otakudesu/jujutsu-kaisen-s3',
    },
    {
      title: 'Chainsaw Man',
      poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
      animeId: 'chainsaw-man-reze',
      href: '/anime/otakudesu/chainsaw-man-reze',
    },
  ],
};

export const mockEpisodeStream: EpisodeStreamData = {
  title: 'Solo Leveling: Arise Episode 12 Subtitle Indonesia',
  animeId: 'solo-leveling-s2',
  defaultStreamingUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?autoplay=0',
  hasPrevEpisode: true,
  prevEpisode: {
    title: 'Episode 11',
    episodeId: 'solo-leveling-ep-11',
    href: '/watch/otakudesu/solo-leveling-ep-11',
  },
  hasNextEpisode: false,
  nextEpisode: null,
  streams: [
    { server: 'Server Utama (HD)', url: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?autoplay=0' },
    { server: 'Server VIP (1080p)', url: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?autoplay=0' },
    { server: 'Server Alternatif 2', url: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?autoplay=0' },
  ],
};

// --- DONGHUA MOCKS (16 Items) ---
export const mockDonghuaList: DonghuaItem[] = [
  {
    title: 'Perfect World (Wanmei Shijie)',
    slug: 'perfect-world',
    poster: 'https://donghive.vip/wp-content/uploads/2025/02/perfect-world-poster-1-rotated.jpg',
    synopsis: 'Lahir di dunia unik yang diberkahi para dewa, Shi Hao mengarungi jalan kultivasi tak tertandingi menantang takdir semesta.',
    rating: '9.9',
    status: 'Ongoing',
    episodes: 204,
    genres: ['Action', 'Fantasy', 'Cultivation', 'Adventure', 'Martial Arts'],
  },
  {
    title: 'Soul Land 2: The Peerless Tang Clan',
    slug: 'soul-land-2',
    poster: 'https://cdn.myanimelist.net/images/anime/1041/136706.jpg',
    synopsis: 'Sepuluh ribu tahun setelah berdirinya Tang San, Sekte Tang telah menurun. Generasi penerus jenius baru bangkit di Shrek Academy.',
    rating: '9.8',
    status: 'Ongoing',
    episodes: 90,
    genres: ['Action', 'Fantasy', 'School', 'Supernatural', 'Martial Arts'],
  },
  {
    title: 'Battle Through the Heavens (Fights Break Sphere)',
    slug: 'btth',
    poster: 'https://cdn.myanimelist.net/images/anime/1660/125866.jpg',
    synopsis: 'Kisah Xiao Yan yang pernah kehilangan kekuatannya kini menguasai Heavenly Flames dan membantai musuh demi membalas dendam klannya.',
    rating: '9.9',
    status: 'Ongoing',
    episodes: 120,
    genres: ['Action', 'Cultivation', 'Fantasy', 'Adventure', 'Romance'],
  },
  {
    title: 'Swallowed Star (Luo Feng)',
    slug: 'swallowed-star',
    poster: 'https://cdn.myanimelist.net/images/anime/1169/110599.jpg',
    synopsis: 'Peradaban bumi di masa depan terancam monster mutan virus RR. Luo Feng bertekad menjadi pejuang terkuat dan menjelajah galaksi.',
    rating: '9.7',
    status: 'Ongoing',
    episodes: 135,
    genres: ['Action', 'Sci-Fi', 'Cultivation', 'Adventure'],
  },
  {
    title: 'Renegade Immortal (Xian Ni)',
    slug: 'renegade-immortal',
    poster: 'https://cdn.myanimelist.net/images/anime/1077/137682.jpg',
    synopsis: 'Wang Lin, pemuda biasa tanpa bakat spiritual, mengandalkan manik misterius dan keteguhan hati berdarah dingin untuk menapaki jalan keabadian.',
    rating: '9.9',
    status: 'Ongoing',
    episodes: 78,
    genres: ['Action', 'Cultivation', 'Fantasy', 'Dark Fantasy', 'Martial Arts'],
  },
  {
    title: 'A Will Eternal Season 3 (Yi Nian Yong Heng)',
    slug: 'a-will-eternal',
    poster: 'https://cdn.myanimelist.net/images/anime/1004/108920.jpg',
    synopsis: 'Bai Xiaochun, pemuda pengecut yang takut mati, selalu memicu kekacauan besar dalam usahanya mengejar hidup abadi.',
    rating: '9.6',
    status: 'Ongoing',
    episodes: 115,
    genres: ['Action', 'Comedy', 'Cultivation', 'Fantasy'],
  },
  {
    title: 'Shrouding the Heavens (Zhe Tian)',
    slug: 'shrouding-the-heavens',
    poster: 'https://cdn.myanimelist.net/images/anime/1063/135118.jpg',
    synopsis: 'Sembilan naga raksasa menarik peti perunggu kuno melintasi langit berbintang, membawa Ye Fan ke dunia kultivasi tanpa batas.',
    rating: '9.5',
    status: 'Ongoing',
    episodes: 85,
    genres: ['Action', 'Cultivation', 'Fantasy', 'Mystery', 'Sci-Fi'],
  },
  {
    title: 'Martial Universe Season 4 (Wu Dong Qian Kun)',
    slug: 'martial-universe',
    poster: 'https://cdn.myanimelist.net/images/anime/1792/101831.jpg',
    synopsis: 'Lin Dong membalas dendam klan Lin dengan bantuan jimat batu misterius dan menguasai Seni Bela Diri Leluhur Kuno.',
    rating: '9.4',
    status: 'Ongoing',
    episodes: 48,
    genres: ['Action', 'Cultivation', 'Fantasy', 'Martial Arts'],
  },
  {
    title: 'Stellar Transformation (Xing Chen Bian)',
    slug: 'stellar-transformation',
    poster: 'https://cdn.myanimelist.net/images/anime/1150/96112.jpg',
    synopsis: 'Qin Yu mengatasi kelemahan meridian fisiknya melalui latihan tubuh ekstrem dan Kristal Meteorik Luar Angkasa.',
    rating: '9.3',
    status: 'Completed',
    episodes: 65,
    genres: ['Action', 'Cultivation', 'Sci-Fi', 'Fantasy'],
  },
  {
    title: "Record of a Mortal's Journey to Immortality",
    slug: 'rmji',
    poster: 'https://cdn.myanimelist.net/images/anime/1429/108922.jpg',
    synopsis: 'Han Li, anak desa miskin dan penuh kehati-hatian, bertahan hidup di dunia kultivasi berbahaya yang penuh pengkhianatan.',
    rating: '9.9',
    status: 'Ongoing',
    episodes: 125,
    genres: ['Action', 'Cultivation', 'Adventure', 'Fantasy'],
  },
  {
    title: 'Jade Dynasty Season 2 (Zhu Xian)',
    slug: 'jade-dynasty',
    poster: 'https://cdn.myanimelist.net/images/anime/1202/125867.jpg',
    synopsis: 'Zhang Xiaofan selamat dari pembantaian desa Caomiao dan terjerumus ke pusaran konflik jalan lurus dan sekte sesat.',
    rating: '9.5',
    status: 'Ongoing',
    episodes: 52,
    genres: ['Action', 'Fantasy', 'Cultivation', 'Drama', 'Romance'],
  },
  {
    title: 'Against the Gods (Ni Tian Xie Shen)',
    slug: 'against-the-gods',
    poster: 'https://cdn.myanimelist.net/images/anime/1199/139366.jpg',
    synopsis: 'Yun Che bangkit kembali dengan Mutiara Racun Langit dan garis keturunan Dewa Jahat untuk membalikkan surga.',
    rating: '9.4',
    status: 'Ongoing',
    episodes: 45,
    genres: ['Action', 'Cultivation', 'Fantasy', 'Harem', 'Martial Arts'],
  },
  {
    title: 'Big Brother Season 2 (My Heroic Husband)',
    slug: 'big-brother',
    poster: 'https://cdn.myanimelist.net/images/anime/1676/133034.jpg',
    synopsis: 'Li Changshou bereinkarnasi ke zaman kuno sebelum perang Dewa, selalu bersembunyi dan tidak pernah menunjukkan lebih dari 10% kekuatannya.',
    rating: '9.6',
    status: 'Ongoing',
    episodes: 60,
    genres: ['Comedy', 'Cultivation', 'Fantasy', 'Isekai', 'Action'],
  },
  {
    title: 'Apotheosis (Bai Lian Cheng Shen)',
    slug: 'apotheosis',
    poster: 'https://cdn.myanimelist.net/images/anime/1915/129759.jpg',
    synopsis: 'Luo Zheng dijadikan samsak manusia setelah keluarganya jatuh, namun ia menemukan kitab kuno yang mengubah tubuhnya menjadi senjata ilahi.',
    rating: '9.3',
    status: 'Ongoing',
    episodes: 98,
    genres: ['Action', 'Cultivation', 'Martial Arts', 'Fantasy'],
  },
  {
    title: 'Tales of Demons and Gods (Yao Shen Ji)',
    slug: 'tales-of-demons-and-gods',
    poster: 'https://cdn.myanimelist.net/images/anime/1067/92842.jpg',
    synopsis: 'Nie Li kembali ke masa mudanya saat kota Glory masih utuh dengan ingatan masa depan dari Buku Roh Iblis Ruang dan Waktu.',
    rating: '9.2',
    status: 'Ongoing',
    episodes: 340,
    genres: ['Action', 'Fantasy', 'Adventure', 'Cultivation', 'Isekai'],
  },
  {
    title: "The King's Avatar S3 (Quan Zhi Gao Shou)",
    slug: 'the-kings-avatar',
    poster: 'https://cdn.myanimelist.net/images/anime/1004/142991.jpg',
    synopsis: 'Dewa game Ye Xiu diusir dari tim profesionalnya dan memulai kembali perjuangannya dari warung internet menuju puncak Glory.',
    rating: '9.7',
    status: 'Completed',
    episodes: 36,
    genres: ['Action', 'Game', 'Sports', 'Drama'],
  },
];

export const mockDonghuaDetail: DonghuaDetail = {
  title: 'Perfect World (Wanmei Shijie)',
  poster: 'https://donghive.vip/wp-content/uploads/2025/02/perfect-world-poster-1-rotated.jpg',
  rating: '9.9',
  synopsis: `Dilahirkan di dunia unik di mana desa-desa berjuang untuk bertahan hidup melawan binatang buas kuno, Shi Hao adalah seorang jenius yang diberkahi oleh surga dengan Tulang Tertinggi.\n\nNamun, takdirnya dirampas oleh kerabat dekatnya sendiri saat masih bayi. Ditinggalkan untuk mati di Desa Batu yang terpencil, ia bangkit kembali berkat bimbingan Pohon Dedalu Willow misterius, memulai legenda tak tertandingi menantang para penguasa alam semesta.`,
  info: {
    'Status': 'Ongoing',
    'Studio': 'Sparkly Key Animation',
    'Tipe': 'Donghua 3D',
    'Rilis': '2021 - Sekarang',
    'Durasi': '20 Menit / Episode',
    'Negara': 'China (Tencent Video)',
  },
  genres: ['Action', 'Adventure', 'Fantasy', 'Martial Arts', 'Cultivation'],
  episodes: [
    {
      episode: 204,
      title: 'Perfect World Episode 204 Subtitle Indonesia',
      slug: 'perfect-world-episode-204-sub-indo',
      date: '23 Sep 2026',
    },
    {
      episode: 203,
      title: 'Perfect World Episode 203 Subtitle Indonesia',
      slug: 'perfect-world-episode-203-sub-indo',
      date: '16 Sep 2026',
    },
    {
      episode: 202,
      title: 'Perfect World Episode 202 Subtitle Indonesia',
      slug: 'perfect-world-episode-202-sub-indo',
      date: '09 Sep 2026',
    },
    {
      episode: 1,
      title: 'Perfect World Episode 01 Subtitle Indonesia',
      slug: 'perfect-world-episode-1-sub-indo',
      date: '23 Apr 2021',
    },
  ],
  recommendations: [
    {
      title: 'Battle Through the Heavens',
      slug: 'btth',
      poster: 'https://cdn.myanimelist.net/images/anime/1660/125866.jpg',
    },
    {
      title: 'Renegade Immortal',
      slug: 'renegade-immortal',
      poster: 'https://cdn.myanimelist.net/images/anime/1077/137682.jpg',
    },
  ],
};

export const mockDonghuaEpisodeStream: DonghuaEpisodeStream = {
  title: 'Perfect World Episode 204 Subtitle Indonesia',
  release_date: '23 September 2026',
  navigation: {
    prev_slug: 'perfect-world-episode-203-sub-indo',
    next_slug: null,
    all_slug: 'perfect-world',
  },
  streams: [
    {
      server: 'Tencent Official Embed',
      url: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ?autoplay=0',
    },
    {
      server: 'Dailymotion Fast Stream',
      url: 'https://geo.dailymotion.com/player/xid0t.html?video=k7Jpm0NmHwS5grCzuwq',
    },
  ],
};

// --- COMIC / MANGA / MANHWA / MANHUA (16 Items) ---
export const mockComicList: ComicItem[] = [
  {
    manga_id: 'revenge-iron-blooded-sword-hound',
    title: 'Revenge of the Iron-Blooded Sword Hound',
    alternative_title: '철혈검가 사냥개의 회귀',
    description: 'Anjing pemburu keluarga Baskerville dieksekusi setelah dikhianati. Kembali ke 40 tahun lalu, kini saatnya membalas dendam.',
    cover: 'https://assets.shngm.id/thumbnail/cover/f99039ce619f.jpeg',
    cover_portrait: 'https://assets.shngm.id/thumbnail/image/d96303ba-bada-4003-aba8-08192706a941.jpg',
    status: 'Ongoing',
    release_year: '2023',
    country: 'KR',
    rating: 9.8,
    views: 41352571,
    bookmarks: 81473,
    latest_chapter: 181,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Fantasy', slug: 'fantasy' }, { name: 'Revenge', slug: 'revenge' }],
  },
  {
    manga_id: 'omniscient-reader-viewpoint',
    title: "Omniscient Reader's Viewpoint",
    alternative_title: '전지적 독자 시점',
    description: 'Dunia novel apokaliptik yang hanya dibaca oleh Dokja tiba-tiba menjadi kenyataan. Hanya dia yang tahu akhir dari dunia ini.',
    cover: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2020',
    country: 'KR',
    rating: 9.9,
    views: 89000000,
    bookmarks: 145000,
    latest_chapter: 225,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Fantasy', slug: 'fantasy' }, { name: 'Supernatural', slug: 'supernatural' }],
  },
  {
    manga_id: 'the-beginning-after-the-end',
    title: 'The Beginning After The End',
    alternative_title: 'TBATE',
    description: 'Raja Grey bereinkarnasi ke dunia magis baru yang penuh bahaya sebagai Arthur Leywin, anak jenius yang mempelajari sihir sejak balita.',
    cover: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2018',
    country: 'US',
    rating: 9.7,
    views: 52000000,
    bookmarks: 96000,
    latest_chapter: 195,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Magic', slug: 'magic' }, { name: 'Isekai', slug: 'isekai' }],
  },
  {
    manga_id: 'magic-emperor',
    title: 'Magic Emperor (Zhuo Yifan)',
    alternative_title: 'Demonic Emperor',
    description: 'Zhuo Yifan, Kaisar Iblis legendaris, dikhianati dan bereinkarnasi ke tubuh pelayan lumpuh keluarga bangsawan yang hancur.',
    cover: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2019',
    country: 'CN',
    rating: 9.8,
    views: 68000000,
    bookmarks: 112000,
    latest_chapter: 570,
    format: 'Manhua',
    genres: [{ name: 'Cultivation', slug: 'cultivation' }, { name: 'Martial Arts', slug: 'martial-arts' }],
  },
  {
    manga_id: 'solo-max-level-newbie',
    title: 'Solo Max-Level Newbie',
    alternative_title: '나 혼자 만렙 뉴비',
    description: "Sebagai satu-satunya player yang menamatkan game 'Tower of Trials', Jinhyuk siap menaklukkan menara saat game berubah menjadi kenyataan.",
    cover: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2021',
    country: 'KR',
    rating: 9.7,
    views: 39000000,
    bookmarks: 78000,
    latest_chapter: 165,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Game', slug: 'game' }, { name: 'Fantasy', slug: 'fantasy' }],
  },
  {
    manga_id: 'nano-machine',
    title: 'Nano Machine',
    alternative_title: '나노마신',
    description: 'Cheon Yeo-Woon, pangeran terbuang dari Sekte Iblis, disuntikkan Nanomachine dari keturunannya di masa depan.',
    cover: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2020',
    country: 'KR',
    rating: 9.8,
    views: 64000000,
    bookmarks: 104000,
    latest_chapter: 228,
    format: 'Manhwa',
    genres: [{ name: 'Martial Arts', slug: 'martial-arts' }, { name: 'Sci-Fi', slug: 'sci-fi' }, { name: 'Murim', slug: 'murim' }],
  },
  {
    manga_id: 'return-of-the-mount-hua-sect',
    title: 'Return of the Mount Hua Sect',
    alternative_title: '화산귀환',
    description: 'Pendekar Suci Bunga Prem Chung Myung mengorbankan nyawanya mengalahkan Chun Ma, lalu terlahir kembali 100 tahun kemudian di Sekte Mount Hua yang bangkrut.',
    cover: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2021',
    country: 'KR',
    rating: 9.9,
    views: 82000000,
    bookmarks: 138000,
    latest_chapter: 135,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Martial Arts', slug: 'martial-arts' }, { name: 'Comedy', slug: 'comedy' }],
  },
  {
    manga_id: 'mercenary-enrollment',
    title: 'Mercenary Enrollment (Teenage Mercenary)',
    alternative_title: '입학용병',
    description: 'Yu Ijin, satu-satunya anak yang selamat dari kecelakaan pesawat di antah berantah, menjadi tentara bayaran mematikan sebelum kembali ke kehidupan SMA normal di Korea.',
    cover: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2020',
    country: 'KR',
    rating: 9.7,
    views: 74000000,
    bookmarks: 119000,
    latest_chapter: 198,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'School', slug: 'school' }, { name: 'Military', slug: 'military' }],
  },
  {
    manga_id: 'eleceed',
    title: 'Eleceed',
    alternative_title: '일렉시드',
    description: 'Jiwoo, remaja baik hati berkekuatan kecepatan super, bertemu Kayden—penyihir terkuat di dunia yang terluka parah dan terjebak dalam wujud kucing gendut.',
    cover: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2018',
    country: 'KR',
    rating: 9.9,
    views: 95000000,
    bookmarks: 162000,
    latest_chapter: 315,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Comedy', slug: 'comedy' }, { name: 'Supernatural', slug: 'supernatural' }],
  },
  {
    manga_id: 'sss-class-suicide-hunter',
    title: 'SSS-Class Revival Hunter',
    alternative_title: 'SSS급 죽어야 사는 헌터',
    description: 'Gongja Kim mendapatkan skill langka menyalin kemampuan orang yang membunuhnya, dengan harga harus mati terlebih dahulu dan kembali 24 jam ke masa lalu.',
    cover: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2020',
    country: 'KR',
    rating: 9.8,
    views: 45000000,
    bookmarks: 88000,
    latest_chapter: 115,
    format: 'Manhwa',
    genres: [{ name: 'Fantasy', slug: 'fantasy' }, { name: 'Psychological', slug: 'psychological' }, { name: 'Drama', slug: 'drama' }],
  },
  {
    manga_id: 'pick-me-up-infinite-gacha',
    title: 'Pick Me Up, Infinite Gacha',
    alternative_title: '픽 미 업!',
    description: "Loki, pemain rank 1 game mobile strategi paling brutal 'Pick Me Up', kehilangan kesadaran dan terdampar sebagai karakter bintang 1 yang siap dikorbankan.",
    cover: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2022',
    country: 'KR',
    rating: 9.8,
    views: 38000000,
    bookmarks: 72000,
    latest_chapter: 104,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Game', slug: 'game' }, { name: 'Survival', slug: 'survival' }],
  },
  {
    manga_id: 'martial-peak',
    title: 'Martial Peak (Wu Lian Feng Feng)',
    alternative_title: '武炼巅峰',
    description: 'Perjalanan menuju puncak bela diri yang sepi dan berbahaya. Yang Kai, seorang penyapu lantai paviliun Lingxiao, menemukan Buku Hitam Tanpa Kata.',
    cover: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80',
    status: 'Completed',
    release_year: '2018',
    country: 'CN',
    rating: 9.4,
    views: 120000000,
    bookmarks: 180000,
    latest_chapter: 3780,
    format: 'Manhua',
    genres: [{ name: 'Cultivation', slug: 'cultivation' }, { name: 'Harem', slug: 'harem' }, { name: 'Action', slug: 'action' }],
  },
  {
    manga_id: 'jujutsu-kaisen-manga',
    title: 'Jujutsu Kaisen',
    alternative_title: '呪術廻戦',
    description: 'Yuuji Itadori menelan jari terkutuk Ryomen Sukuna dan terjun ke dalam perang berbahaya para penyihir Jujutsu demi menyelamatkan orang lain.',
    cover: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    status: 'Completed',
    release_year: '2018',
    country: 'JP',
    rating: 9.8,
    views: 110000000,
    bookmarks: 210000,
    latest_chapter: 271,
    format: 'Manga',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Supernatural', slug: 'supernatural' }, { name: 'Shounen', slug: 'shounen' }],
  },
  {
    manga_id: 'chainsaw-man-manga',
    title: 'Chainsaw Man (Part 2: Academy Saga)',
    alternative_title: 'チェンソーマン',
    description: 'Denji menjalani kehidupan ganda sebagai siswa SMA biasa sambil menyembunyikan identitasnya sebagai Chainsaw Man di tengah ancaman War Devil.',
    cover: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2018',
    country: 'JP',
    rating: 9.7,
    views: 88000000,
    bookmarks: 175000,
    latest_chapter: 178,
    format: 'Manga',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Horror', slug: 'horror' }, { name: 'Comedy', slug: 'comedy' }],
  },
  {
    manga_id: 'one-piece-manga',
    title: 'One Piece',
    alternative_title: 'ONE PIECE',
    description: 'Monkey D. Luffy dan Bajak Laut Topi Jerami menjelajahi Grand Line demi menemukan harta karun terbesar di dunia: One Piece.',
    cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '1997',
    country: 'JP',
    rating: 9.9,
    views: 240000000,
    bookmarks: 350000,
    latest_chapter: 1126,
    format: 'Manga',
    genres: [{ name: 'Adventure', slug: 'adventure' }, { name: 'Action', slug: 'action' }, { name: 'Shounen', slug: 'shounen' }],
  },
  {
    manga_id: 'lookism',
    title: 'Lookism',
    alternative_title: '외모지상주의',
    description: 'Daniel Park, remaja bertubuh gemuk yang selalu dirundung, secara ajaib terbangun dengan tubuh kedua yang tampan, tinggi, dan sempurna.',
    cover: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    cover_portrait: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
    status: 'Ongoing',
    release_year: '2014',
    country: 'KR',
    rating: 9.6,
    views: 130000000,
    bookmarks: 195000,
    latest_chapter: 520,
    format: 'Manhwa',
    genres: [{ name: 'Action', slug: 'action' }, { name: 'Drama', slug: 'drama' }, { name: 'Martial Arts', slug: 'martial-arts' }],
  },
];

export const mockComicDetail: ComicDetail = {
  ...mockComicList[0],
  authors: [{ name: 'Step on a lego', slug: 'step-on-a-lego' }],
  artists: [{ name: 'Redice Studio', slug: 'redice-studio' }],
};

export const mockChapters: ChapterItem[] = [
  {
    chapter_id: 'ch-181',
    manga_id: 'revenge-iron-blooded-sword-hound',
    chapter_number: 181,
    chapter_title: 'Pertarungan Garis Depan',
    views: 110387,
    release_date: '2026-09-20',
  },
  {
    chapter_id: 'ch-180',
    manga_id: 'revenge-iron-blooded-sword-hound',
    chapter_number: 180,
    chapter_title: 'Perangkap Malam',
    views: 145000,
    release_date: '2026-09-13',
  },
  {
    chapter_id: 'ch-179',
    manga_id: 'revenge-iron-blooded-sword-hound',
    chapter_number: 179,
    chapter_title: 'Pembalasan Dimulai',
    views: 160000,
    release_date: '2026-09-06',
  },
  {
    chapter_id: 'ch-1',
    manga_id: 'revenge-iron-blooded-sword-hound',
    chapter_number: 1,
    chapter_title: 'Anjing Pemburu yang Dibuang',
    views: 950000,
    release_date: '2023-01-15',
  },
];

export const mockChapterReader: ChapterReaderData = {
  chapter_id: 'ch-181',
  manga_id: 'revenge-iron-blooded-sword-hound',
  chapter_number: 181,
  chapter_title: 'Pertarungan Garis Depan Sub Indo',
  views: 110387,
  release_date: '2026-09-20',
  prev_chapter: 'ch-180',
  next_chapter: null,
  total_images: 5,
  images: [
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1000&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1000&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1000&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1563089145-599997674d42?w=1000&auto=format&fit=crop&q=80',
  ],
};

// --- GENRES (24 Items) ---
export const mockGenreList: GenreItem[] = [
  { name: 'Action', slug: 'action', count: 1240, description: 'Pertarungan intens, jurus mematikan, dan adegan laga bertensi tinggi.' },
  { name: 'Fantasy', slug: 'fantasy', count: 980, description: 'Dunia mistis penuh sihir, monster, dewa kuno, dan kekuatan ajaib.' },
  { name: 'Cultivation', slug: 'cultivation', count: 420, description: 'Perjalanan abadi menembus batas spiritual dan ranah kultivasi xianxia.' },
  { name: 'Martial Arts', slug: 'martial-arts', count: 390, description: 'Seni bela diri wuxia dan murim berpedang tajam serta aliran kungfu legendaris.' },
  { name: 'Adventure', slug: 'adventure', count: 850, description: 'Penjelajahan menjelajahi benua asing, dungeon kuno, dan pulau tersembunyi.' },
  { name: 'Isekai', slug: 'isekai', count: 630, description: 'Terlempar atau bereinkarnasi ke dunia lain dengan cheat atau misi baru.' },
  { name: 'Supernatural', slug: 'supernatural', count: 520, description: 'Fenomena paranormal, roh, iblis, dan makhluk dari alam lain.' },
  { name: 'Shounen', slug: 'shounen', count: 740, description: 'Cerita kepahlawanan, persahabatan, tekad baja, dan impian besar generasi muda.' },
  { name: 'Seinen', slug: 'seinen', count: 510, description: 'Tema narasi lebih matang, psikologi kompleks, dan intrik politik tajam.' },
  { name: 'Sci-Fi', slug: 'sci-fi', count: 430, description: 'Teknologi futuristik, robotika canggih, perjalanan antariksa, dan distopia siber.' },
  { name: 'Comedy', slug: 'comedy', count: 590, description: 'Tingkah konyol, parodi jenaka, dan humor menyegarkan pengocok perut.' },
  { name: 'Romance', slug: 'romance', count: 680, description: 'Kisah cinta menyentuh hati, romansa manis, dan dinamika emosional mendalam.' },
  { name: 'Mystery', slug: 'mystery', count: 310, description: 'Teka-teki kriminalitas, investigasi cerdas, konspirasi, dan misteri tak terungkap.' },
  { name: 'Psychological', slug: 'psychological', count: 280, description: 'Perang akal pikiran, manipulasi psikologis, dan pergulatan batin karakter.' },
  { name: 'Drama', slug: 'drama', count: 490, description: 'Konflik interpersonal mendalam, cobaan hidup, dan drama emosional.' },
  { name: 'Slice of Life', slug: 'slice-of-life', count: 360, description: 'Kisah keseharian yang hangat, tenang, dan merefleksikan kedamaian hidup.' },
  { name: 'Game', slug: 'game', count: 290, description: 'Dunia game realitas virtual (VR), leveling rank, dan strategi gamer pro.' },
  { name: 'Reincarnation', slug: 'reincarnation', count: 450, description: 'Kembali ke masa lalu atau terlahir lagi membawa ingatan masa lampau.' },
  { name: 'Magic', slug: 'magic', count: 610, description: 'Kajian mantra kuno, sekolah sihir, lingkaran rune, dan artefak suci.' },
  { name: 'School', slug: 'school', count: 440, description: 'Dinamika kehidupan sekolah menengah atas, klub ekstrakurikuler, dan festival akademi.' },
  { name: 'Horror', slug: 'horror', count: 190, description: 'Suasana mencekam, kengerian teror menyeramkan, dan makhluk mimpi buruk.' },
  { name: 'Mecha', slug: 'mecha', count: 210, description: 'Pertarungan robot raksasa lapis baja dalam medan tempur medan perang masa depan.' },
  { name: 'Sports', slug: 'sports', count: 180, description: 'Semangat kompetisi atletik, sepak bola, basket, dan tekad juara lapangan.' },
  { name: 'Historical', slug: 'historical', count: 230, description: 'Latar kekaisaran dinasti kuno, perang zaman feodal, dan catatan sejarah.' },
];

// --- JADWAL RILIS / SCHEDULE (Senin - Minggu) ---
export const mockSchedule: ScheduleDay[] = [
  {
    day: 'Senin',
    dayEn: 'Monday',
    entries: [
      {
        title: 'Tower of God Season 2: Workshop Battle',
        animeId: 'tower-of-god-s2',
        poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
        time: '21:00 WIB',
        episode: 'Episode 12',
        genres: ['Action', 'Fantasy', 'Mystery'],
        type: 'anime',
      },
      {
        title: 'Bleach: Thousand-Year Blood War Pt. 3',
        animeId: 'bleach-tybw-pt3',
        poster: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
        time: '23:00 WIB',
        episode: 'Episode 32',
        genres: ['Action', 'Supernatural'],
        type: 'anime',
      },
      {
        title: 'Vinland Saga Season 3',
        animeId: 'vinland-saga-s3',
        poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
        time: '22:30 WIB',
        episode: 'Episode 10',
        genres: ['Action', 'Historical', 'Drama'],
        type: 'anime',
      },
    ],
  },
  {
    day: 'Selasa',
    dayEn: 'Tuesday',
    entries: [
      {
        title: 'Blue Lock Season 2: U-20 Match',
        animeId: 'blue-lock-s2',
        poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
        time: '23:30 WIB',
        episode: 'Episode 05',
        genres: ['Sports', 'Drama'],
        type: 'anime',
      },
      {
        title: 'Renegade Immortal (Xian Ni)',
        animeId: 'renegade-immortal',
        poster: 'https://cdn.myanimelist.net/images/anime/1077/137682.jpg',
        time: '10:00 WIB',
        episode: 'Episode 78',
        genres: ['Action', 'Cultivation'],
        type: 'donghua',
      },
      {
        title: 'Wind Breaker: Bofurin Legend',
        animeId: 'wind-breaker',
        poster: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&auto=format&fit=crop&q=80',
        time: '22:00 WIB',
        episode: 'Episode 13',
        genres: ['Action', 'School'],
        type: 'anime',
      },
      {
        title: 'Against the Gods (Ni Tian Xie Shen)',
        animeId: 'against-the-gods',
        poster: 'https://cdn.myanimelist.net/images/anime/1199/139366.jpg',
        time: '11:00 WIB',
        episode: 'Episode 45',
        genres: ['Action', 'Cultivation', 'Fantasy'],
        type: 'donghua',
      },
    ],
  },
  {
    day: 'Rabu',
    dayEn: 'Wednesday',
    isToday: true,
    entries: [
      {
        title: 'Oshi no Ko Season 2',
        animeId: 'oshi-no-ko-s2',
        poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
        time: '22:00 WIB',
        episode: 'Episode 11',
        genres: ['Drama', 'Supernatural'],
        type: 'anime',
      },
      {
        title: 'Swallowed Star (Luo Feng)',
        animeId: 'swallowed-star',
        poster: 'https://cdn.myanimelist.net/images/anime/1169/110599.jpg',
        time: '10:00 WIB',
        episode: 'Episode 135',
        genres: ['Action', 'Sci-Fi', 'Cultivation'],
        type: 'donghua',
      },
      {
        title: 'Re:Zero Season 3',
        animeId: 're-zero-s3',
        poster: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
        time: '21:30 WIB',
        episode: 'Episode 16',
        genres: ['Fantasy', 'Psychological', 'Isekai'],
        type: 'anime',
      },
      {
        title: 'Apotheosis (Bai Lian Cheng Shen)',
        animeId: 'apotheosis',
        poster: 'https://cdn.myanimelist.net/images/anime/1915/129759.jpg',
        time: '11:30 WIB',
        episode: 'Episode 98',
        genres: ['Action', 'Cultivation'],
        type: 'donghua',
      },
    ],
  },
  {
    day: 'Kamis',
    dayEn: 'Thursday',
    entries: [
      {
        title: 'Jujutsu Kaisen: Culling Game Arc',
        animeId: 'jujutsu-kaisen-s3',
        poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
        time: '23:56 WIB',
        episode: 'Episode 08',
        genres: ['Action', 'Supernatural'],
        type: 'anime',
      },
      {
        title: 'DanMachi Season 5',
        animeId: 'danmachi-s5',
        poster: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=600&auto=format&fit=crop&q=80',
        time: '21:30 WIB',
        episode: 'Episode 09',
        genres: ['Action', 'Fantasy', 'Adventure'],
        type: 'anime',
      },
      {
        title: 'A Will Eternal Season 3',
        animeId: 'a-will-eternal',
        poster: 'https://cdn.myanimelist.net/images/anime/1004/108920.jpg',
        time: '10:00 WIB',
        episode: 'Episode 115',
        genres: ['Action', 'Comedy', 'Cultivation'],
        type: 'donghua',
      },
      {
        title: 'Big Brother Season 2',
        animeId: 'big-brother',
        poster: 'https://cdn.myanimelist.net/images/anime/1676/133034.jpg',
        time: '11:00 WIB',
        episode: 'Episode 60',
        genres: ['Comedy', 'Cultivation'],
        type: 'donghua',
      },
    ],
  },
  {
    day: 'Jumat',
    dayEn: 'Friday',
    entries: [
      {
        title: "Frieren: Beyond Journey's End S2",
        animeId: 'frieren-s2',
        poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
        time: '22:00 WIB',
        episode: 'Episode 06',
        genres: ['Adventure', 'Fantasy', 'Drama'],
        type: 'anime',
      },
      {
        title: 'Battle Through the Heavens',
        animeId: 'btth',
        poster: 'https://cdn.myanimelist.net/images/anime/1660/125866.jpg',
        time: '10:00 WIB',
        episode: 'Episode 120',
        genres: ['Action', 'Cultivation', 'Fantasy'],
        type: 'donghua',
      },
      {
        title: 'Shangri-La Frontier S2',
        animeId: 'shangri-la-frontier-s2',
        poster: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
        time: '17:00 WIB',
        episode: 'Episode 07',
        genres: ['Action', 'Game', 'Adventure'],
        type: 'anime',
      },
      {
        title: 'Jade Dynasty Season 2',
        animeId: 'jade-dynasty',
        poster: 'https://cdn.myanimelist.net/images/anime/1202/125867.jpg',
        time: '11:00 WIB',
        episode: 'Episode 52',
        genres: ['Action', 'Cultivation', 'Romance'],
        type: 'donghua',
      },
    ],
  },
  {
    day: 'Sabtu',
    dayEn: 'Saturday',
    entries: [
      {
        title: 'Solo Leveling: Arise from the Shadow',
        animeId: 'solo-leveling-s2',
        poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
        time: '23:00 WIB',
        episode: 'Episode 12',
        genres: ['Action', 'Fantasy'],
        type: 'anime',
      },
      {
        title: 'Soul Land 2: The Peerless Tang Clan',
        animeId: 'soul-land-2',
        poster: 'https://cdn.myanimelist.net/images/anime/1498/136867.jpg',
        time: '10:00 WIB',
        episode: 'Episode 90',
        genres: ['Action', 'Fantasy', 'Cultivation'],
        type: 'donghua',
      },
      {
        title: 'My Hero Academia Season 7',
        animeId: 'my-hero-academia-s7',
        poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
        time: '16:30 WIB',
        episode: 'Episode 21',
        genres: ['Action', 'Shounen'],
        type: 'anime',
      },
      {
        title: 'Kaiju No. 8 Season 2',
        animeId: 'kaiju-no-8-s2',
        poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
        time: '22:00 WIB',
        episode: 'Episode 12',
        genres: ['Action', 'Sci-Fi'],
        type: 'anime',
      },
    ],
  },
  {
    day: 'Minggu',
    dayEn: 'Sunday',
    entries: [
      {
        title: 'Demon Slayer: Infinity Castle Arc',
        animeId: 'demon-slayer-infinity-castle',
        poster: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
        time: '22:15 WIB',
        episode: 'Episode 04',
        genres: ['Action', 'Supernatural'],
        type: 'anime',
      },
      {
        title: 'Chainsaw Man: Reze Arc',
        animeId: 'chainsaw-man-reze',
        poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
        time: '23:00 WIB',
        episode: 'Episode 02',
        genres: ['Action', 'Horror'],
        type: 'anime',
      },
      {
        title: 'One Piece: Egghead Island',
        animeId: 'one-piece',
        poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
        time: '09:30 WIB',
        episode: 'Episode 1125',
        genres: ['Action', 'Adventure'],
        type: 'anime',
      },
      {
        title: 'Shrouding the Heavens (Zhe Tian)',
        animeId: 'shrouding-the-heavens',
        poster: 'https://cdn.myanimelist.net/images/anime/1063/135118.jpg',
        time: '10:00 WIB',
        episode: 'Episode 85',
        genres: ['Action', 'Cultivation'],
        type: 'donghua',
      },
    ],
  },
];

// --- COMIC SCHEDULE (7 Days) ---
export const mockComicSchedule: ComicScheduleDay[] = [
  {
    day: 'Senin',
    dayEn: 'Monday',
    entries: [
      {
        title: 'Revenge of the Iron-Blooded Sword Hound',
        mangaId: 'revenge-iron-blooded-sword-hound',
        poster: 'https://assets.shngm.id/thumbnail/cover/f99039ce619f.jpeg',
        time: '19:00 WIB',
        chapter: 'Chapter 182',
        format: 'Manhwa',
        genres: ['Action', 'Fantasy', 'Revenge'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Return of the Mount Hua Sect',
        mangaId: 'return-of-the-mount-hua-sect',
        poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
        time: '20:30 WIB',
        chapter: 'Chapter 145',
        format: 'Manhwa',
        genres: ['Action', 'Martial Arts', 'Comedy'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Martial Peak (Wudao Dianfeng)',
        mangaId: 'martial-peak',
        poster: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
        time: '14:00 WIB',
        chapter: 'Chapter 3850',
        format: 'Manhua',
        genres: ['Action', 'Cultivation', 'Fantasy'],
        status: 'Ongoing',
        country: 'CN',
      },
      {
        title: 'Berserk of Gluttony (Manga)',
        mangaId: 'berserk-of-gluttony',
        poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
        time: '17:00 WIB',
        chapter: 'Chapter 62',
        format: 'Manga',
        genres: ['Action', 'Dark Fantasy'],
        status: 'Ongoing',
        country: 'JP',
      },
    ],
  },
  {
    day: 'Selasa',
    dayEn: 'Tuesday',
    entries: [
      {
        title: "Omniscient Reader's Viewpoint",
        mangaId: 'omniscient-reader-viewpoint',
        poster: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
        time: '21:00 WIB',
        chapter: 'Chapter 226',
        format: 'Manhwa',
        genres: ['Action', 'Fantasy', 'Supernatural'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'SSS-Class Suicide Hunter',
        mangaId: 'sss-class-suicide-hunter',
        poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
        time: '20:00 WIB',
        chapter: 'Chapter 115',
        format: 'Manhwa',
        genres: ['Fantasy', 'Action', 'Psychological'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Eleceed',
        mangaId: 'eleceed',
        poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
        time: '22:00 WIB',
        chapter: 'Chapter 318',
        format: 'Manhwa',
        genres: ['Action', 'Comedy', 'Superpower'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Yuan Zun (Dragon Prince Yuan)',
        mangaId: 'yuan-zun',
        poster: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
        time: '15:30 WIB',
        chapter: 'Chapter 720',
        format: 'Manhua',
        genres: ['Action', 'Fantasy', 'Cultivation'],
        status: 'Ongoing',
        country: 'CN',
      },
    ],
  },
  {
    day: 'Rabu',
    dayEn: 'Wednesday',
    isToday: true,
    entries: [
      {
        title: 'The Beginning After The End',
        mangaId: 'the-beginning-after-the-end',
        poster: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
        time: '20:00 WIB',
        chapter: 'Chapter 196',
        format: 'Manhwa',
        genres: ['Action', 'Magic', 'Isekai'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Nano Machine',
        mangaId: 'nano-machine',
        poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
        time: '21:30 WIB',
        chapter: 'Chapter 235',
        format: 'Manhwa',
        genres: ['Action', 'Murim', 'Sci-Fi'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Tales of Demons and Gods (Yao Shen Ji)',
        mangaId: 'tales-of-demons-and-gods',
        poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
        time: '16:00 WIB',
        chapter: 'Chapter 465',
        format: 'Manhua',
        genres: ['Action', 'Cultivation', 'Reincarnation'],
        status: 'Ongoing',
        country: 'CN',
      },
      {
        title: 'One Punch Man (Murata)',
        mangaId: 'one-punch-man',
        poster: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
        time: '23:00 WIB',
        chapter: 'Chapter 204',
        format: 'Manga',
        genres: ['Action', 'Comedy', 'Superhero'],
        status: 'Ongoing',
        country: 'JP',
      },
    ],
  },
  {
    day: 'Kamis',
    dayEn: 'Thursday',
    entries: [
      {
        title: 'Magic Emperor (Zhuo Yifan)',
        mangaId: 'magic-emperor',
        poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
        time: '18:00 WIB',
        chapter: 'Chapter 598',
        format: 'Manhua',
        genres: ['Action', 'Fantasy', 'Reincarnation'],
        status: 'Ongoing',
        country: 'CN',
      },
      {
        title: 'Mercenary Enrollment (Teenage Mercenary)',
        mangaId: 'mercenary-enrollment',
        poster: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
        time: '20:00 WIB',
        chapter: 'Chapter 210',
        format: 'Manhwa',
        genres: ['Action', 'Drama', 'School'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Lookism',
        mangaId: 'lookism',
        poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
        time: '21:00 WIB',
        chapter: 'Chapter 524',
        format: 'Manhwa',
        genres: ['Action', 'Drama', 'Supernatural'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Tokyo Revengers: Baji Keisuke Epilogue',
        mangaId: 'tokyo-revengers',
        poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
        time: '19:30 WIB',
        chapter: 'Chapter 14',
        format: 'Manga',
        genres: ['Action', 'Drama', 'Shounen'],
        status: 'Ongoing',
        country: 'JP',
      },
    ],
  },
  {
    day: 'Jumat',
    dayEn: 'Friday',
    entries: [
      {
        title: 'Wind Breaker (Manhwa)',
        mangaId: 'wind-breaker-manhwa',
        poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
        time: '20:30 WIB',
        chapter: 'Chapter 518',
        format: 'Manhwa',
        genres: ['Sports', 'Drama', 'Action'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Solo Leveling: Ragnarok',
        mangaId: 'solo-leveling-ragnarok',
        poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
        time: '22:00 WIB',
        chapter: 'Chapter 34',
        format: 'Manhwa',
        genres: ['Action', 'Fantasy', 'Supernatural'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'The Greatest Estate Developer',
        mangaId: 'the-greatest-estate-developer',
        poster: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
        time: '19:00 WIB',
        chapter: 'Chapter 162',
        format: 'Manhwa',
        genres: ['Comedy', 'Fantasy', 'Isekai'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Dandadan (Manga)',
        mangaId: 'dandadan',
        poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
        time: '21:00 WIB',
        chapter: 'Chapter 168',
        format: 'Manga',
        genres: ['Supernatural', 'Action', 'Comedy'],
        status: 'Ongoing',
        country: 'JP',
      },
    ],
  },
  {
    day: 'Sabtu',
    dayEn: 'Saturday',
    entries: [
      {
        title: 'Jujutsu Kaisen (Manga)',
        mangaId: 'jujutsu-kaisen-manga',
        poster: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
        time: '22:00 WIB',
        chapter: 'Chapter 271',
        format: 'Manga',
        genres: ['Action', 'Supernatural', 'Shounen'],
        status: 'Ongoing',
        country: 'JP',
      },
      {
        title: 'One Piece (Manga)',
        mangaId: 'one-piece-manga',
        poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
        time: '21:30 WIB',
        chapter: 'Chapter 1128',
        format: 'Manga',
        genres: ['Action', 'Adventure', 'Fantasy'],
        status: 'Ongoing',
        country: 'JP',
      },
      {
        title: 'Tower of God',
        mangaId: 'tower-of-god',
        poster: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
        time: '23:00 WIB',
        chapter: 'Chapter 638',
        format: 'Manhwa',
        genres: ['Action', 'Fantasy', 'Mystery'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Soul Land V: Tang San Rebirth',
        mangaId: 'soul-land-v',
        poster: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&auto=format&fit=crop&q=80',
        time: '15:00 WIB',
        chapter: 'Chapter 180',
        format: 'Manhua',
        genres: ['Action', 'Fantasy', 'Romance'],
        status: 'Ongoing',
        country: 'CN',
      },
    ],
  },
  {
    day: 'Minggu',
    dayEn: 'Sunday',
    entries: [
      {
        title: 'Chainsaw Man Part 2 (Manga)',
        mangaId: 'chainsaw-man-manga',
        poster: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
        time: '22:00 WIB',
        chapter: 'Chapter 178',
        format: 'Manga',
        genres: ['Action', 'Horror', 'Supernatural'],
        status: 'Ongoing',
        country: 'JP',
      },
      {
        title: 'Damn Reincarnation',
        mangaId: 'damn-reincarnation',
        poster: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
        time: '20:00 WIB',
        chapter: 'Chapter 89',
        format: 'Manhwa',
        genres: ['Fantasy', 'Action', 'Reincarnation'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Overgeared (Team Argo)',
        mangaId: 'overgeared',
        poster: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
        time: '19:30 WIB',
        chapter: 'Chapter 248',
        format: 'Manhwa',
        genres: ['Action', 'Game', 'Fantasy'],
        status: 'Ongoing',
        country: 'KR',
      },
      {
        title: 'Battle Through the Heavens (Doupo Cangqiong)',
        mangaId: 'battle-through-the-heavens',
        poster: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
        time: '16:30 WIB',
        chapter: 'Chapter 442',
        format: 'Manhua',
        genres: ['Action', 'Cultivation', 'Fantasy'],
        status: 'Ongoing',
        country: 'CN',
      },
    ],
  },
];
